# Generated by Django 4.2.16 on 2026-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_todo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
