# Generated by Django 4.2.16 on 2026-04-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'name']},
        ),
    ]
