# Generated by Django 4.2.16 on 2026-04-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency_days', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='todo',
            name='night_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='one_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='frequency_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
