# Generated by Django 4.2.16 on 2026-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_bill_birthday_todo_night_time_todo_one_off_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
