# Generated by Django 4.2.16 on 2026-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_gratitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gratitude',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='gratitude',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
