# Generated by Django 4.2.16 on 2026-04-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_alter_gratitude_options_gratitude_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_heading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
