# Generated by Django 4.2.16 on 2026-05-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0022_story_people_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='snoozed_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
